import { Inter } from "next/font/google";
import "./globals.css";
// layout.js
// import "../styles/styles.scss";
// import "@/styles/NavbarStyles.scss";
// import "@/styles/styles.scss";
import "../styles/styles.scss";
// import Navbar from "@/components/Navbar";
import Navbar from "../components/Navbar";
import { LuPhone } from "react-icons/lu";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <a
          href="tel:+1234567890"
          className="shake-animate"
          style={{
            position: "fixed",
            bottom: "20%",
            right: "55px",
            zIndex: "10000",
            width: "50px",
            height: "50px",
            background: "#000",
            borderRadius: "10px",
            padding: "10px",
            boxShadow: "0 0 10px rgba(0, 0, 0, 0.2)",
          }}
        >
          <LuPhone style={{ color: "#fff", fontSize: "32px" }} />
        </a>
      </body>
    </html>
  );
}
